# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ringapp', '0031_auto_20150322_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.SmallIntegerField(choices=[(0, 'ring'), (1, 'citation'), (1, 'theorem'), (1, 'citation')])),
                ('status', models.SmallIntegerField(choices=[(-2, 'need info'), (-1, 'declined'), (0, 'pending'), (1, 'accepted'), (2, 'withdrawn')], default=0)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('citation', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
