# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0033_auto_20160407_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='object_type',
            field=models.SmallIntegerField(choices=[(0, 'ring'), (1, 'citation'), (1, 'theorem')]),
        ),
    ]
