# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0034_auto_20160409_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='object_type',
            field=models.SmallIntegerField(choices=[(0, 'ring'), (1, 'citation'), (2, 'theorem'), (3, 'other')]),
        ),
    ]
