# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 15:22
from __future__ import unicode_literals

from django.db import migrations


def rename_domain(apps, schema_editor):
    Site = apps.get_model('sites.Site')
    site_1, created = Site.objects.get_or_create(id=1)
    site_1.domain = 'ringtheory.herokuapp.com'
    site_1.name = 'ringtheory.herokuapp.com'
    site_1.save()


def undo_rename_domain(apps, schema_editor):
    Site = apps.get_model('sites.Site')
    site_1 = Site.objects.get(id=1)
    site_1.domain = 'example.com'
    site_1.name = 'example.com'
    site_1.save()


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('ringapp', '0035_auto_20160526_0049'),
    ]

    operations = [
        migrations.RunPython(rename_domain, reverse_code=undo_rename_domain),
    ]
