# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-16 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0038_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News items'},
        ),
        migrations.AddField(
            model_name='keyword',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
