# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-21 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ringapp', '0040_auto_20170906_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ring',
            name='poster',
        ),
        migrations.AddField(
            model_name='ring',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
