# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0002_initial_data'),
        ('ringapp', '0042_auto_20180115_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
            ],
            options={
                'db_table': 'publications_publication',
                'ordering': ['authors', 'title'],
                'managed': False,
                'proxy': True,
            },
            bases=('publications.publication',),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringapp.Publication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('publication__authors', 'publication__title'),
            },
        ),
    ]
