# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 23:12
from __future__ import unicode_literals

from django.conf import settings
from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'properties.json', app_label='ringapp')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ringapp', '0043_citation_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('definition', models.TextField(max_length=1024)),
                ('symmetric', models.NullBooleanField()),
                ('commutative_only', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ('name',),
            },
        ),
        migrations.RunPython(load_fixture),
    ]
