# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0044_property'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
