# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ringapp', '0045_delete_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.PositiveSmallIntegerField(choices=[(0, '===>'), (1, '<==>')], null=True)),
                ('symmetric', models.NullBooleanField()),
                ('active', models.BooleanField(default=True)),
                ('citation', models.ManyToManyField(blank=True, to='ringapp.Citation')),
            ],
        ),
        migrations.CreateModel(
            name='Metaproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('definition', models.TextField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Metaproperties',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PropertyMetaproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_metaproperty', models.NullBooleanField()),
                ('commutative_only', models.BooleanField(default=False)),
                ('citation', models.ManyToManyField(blank=True, to='ringapp.Citation')),
            ],
            options={
                'verbose_name_plural': 'Property-metaproperty relationships',
            },
        ),
        migrations.CreateModel(
            name='PropertySide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.SmallIntegerField(choices=[(0, ''), (1, 'left and right'), (2, 'left'), (3, 'right'), (4, 'left or right')])),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringapp.Property')),
            ],
            options={
                'verbose_name_plural': 'Property-side pairings',
                'ordering': ('property', 'side'),
            },
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('krull_dim', models.FloatField(blank=True, null=True)),
                ('is_commutative', models.NullBooleanField()),
                ('optional_template', models.CharField(blank=True, default='', max_length=128)),
                ('citation', models.ManyToManyField(blank=True, to='ringapp.Citation')),
                ('keywords', models.ManyToManyField(blank=True, to='ringapp.Keyword')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RingProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_on_left', models.NullBooleanField()),
                ('reason_left', models.CharField(blank=True, max_length=200, null=True)),
                ('has_on_right', models.NullBooleanField()),
                ('reason_right', models.CharField(blank=True, max_length=200, null=True)),
                ('citation_left', models.ManyToManyField(blank=True, related_name='citation_left', to='ringapp.Citation')),
                ('citation_right', models.ManyToManyField(blank=True, related_name='citation_right', to='ringapp.Citation')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringapp.Property')),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringapp.Ring')),
            ],
            options={
                'verbose_name_plural': 'Ring-property relationships',
            },
        ),
        migrations.CreateModel(
            name='Theorem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('statement', models.TextField(max_length=400)),
                ('link', models.URLField(blank=True, null=True)),
                ('commutative_only', models.BooleanField(default=False)),
                ('citation', models.ManyToManyField(blank=True, to='ringapp.Citation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='propertymetaproperty',
            name='example',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ringapp.Ring'),
        ),
        migrations.AddField(
            model_name='propertymetaproperty',
            name='metaproperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringapp.Metaproperty'),
        ),
        migrations.AddField(
            model_name='propertymetaproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringapp.Property'),
        ),
        migrations.AddField(
            model_name='logic',
            name='concs',
            field=models.ManyToManyField(related_name='conclusions', to='ringapp.PropertySide', verbose_name='conclusions'),
        ),
        migrations.AddField(
            model_name='logic',
            name='hyps',
            field=models.ManyToManyField(related_name='hypotheses', to='ringapp.PropertySide', verbose_name='hypotheses'),
        ),
        migrations.AddField(
            model_name='logic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ringproperty',
            unique_together=set([('ring', 'property')]),
        ),
        migrations.AlterUniqueTogether(
            name='propertyside',
            unique_together=set([('property', 'side')]),
        ),
        migrations.AlterUniqueTogether(
            name='propertymetaproperty',
            unique_together=set([('property', 'metaproperty')]),
        ),
    ]
