# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0046_auto_20180115_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='object_type',
            field=models.SmallIntegerField(choices=[(0, 'ring'), (1, 'citation'), (2, 'theorem'), (3, 'other'), (4, 'property of a ring'), (5, 'property'), (6, 'feature')]),
        ),
    ]
