# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0047_auto_20180209_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ring',
            name='krull_dim',
            field=models.CharField(blank=True, default='(unknown)', max_length=16, null=True),
        ),
    ]
