# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0049_suggestion_unread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('definition', models.TextField(max_length=1024)),
                ('symmetric', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Erratum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='A description of the faulty claim and useful information about correcting it.', max_length=400)),
                ('corrected_location', models.ManyToManyField(help_text='References which correct the statement.', related_name='corrected_location', to='ringapp.Citation')),
                ('error_location', models.ForeignKey(help_text='Where the original erroneous statement appeared.', on_delete=django.db.models.deletion.CASCADE, related_name='error_location', to='ringapp.Citation')),
                ('example', models.ForeignKey(blank=True, help_text='A ring acting as a counterexample to the erroneous statement.', null=True, on_delete=django.db.models.deletion.CASCADE, to='ringapp.Ring')),
            ],
            options={
                'verbose_name_plural': 'Errata',
            },
        ),
        migrations.CreateModel(
            name='RingDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_dimension', models.CharField(blank=True, help_text='Indicates magnitude of dimension.', max_length=16)),
                ('right_dimension', models.CharField(blank=True, help_text='Indicates magnitude of dimension.', max_length=16)),
                ('citation', models.ManyToManyField(blank=True, to='ringapp.Citation')),
                ('dimension_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringapp.Dimension')),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringapp.Ring')),
            ],
        ),
        migrations.CreateModel(
            name='RingSubset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subset', models.CharField(help_text='Describes the elements in the indicated subset.', max_length=512)),
                ('citation', models.ManyToManyField(blank=True, to='ringapp.Citation')),
                ('ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringapp.Ring')),
            ],
        ),
        migrations.CreateModel(
            name='Subset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('definition', models.TextField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='ringsubset',
            name='subset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ringapp.Subset'),
        ),
    ]
