# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-27 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0051_auto_20180608_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
        migrations.AddField(
            model_name='property',
            name='citation',
            field=models.ManyToManyField(blank=True, to='ringapp.Citation'),
        ),
    ]
