# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0052_remove_property_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoremCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='theorem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ringapp.TheoremCategory'),
        ),
    ]
