# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-26 02:20
from __future__ import unicode_literals

import django
from django.db import migrations, models


def move_data(apps, schema_editor):
    Theorem = apps.get_model('ringapp', 'Theorem')
    for theorem in Theorem.objects.all():
        cat = theorem.category
        if cat is not None:
            cat.save()
            theorem.categories.add(cat)


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0053_auto_20180912_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='category', to='ringapp.TheoremCategory'),
        ),
        migrations.AddField(
            model_name='theorem',
            name='categories',
            field=models.ManyToManyField(blank=True, to='ringapp.TheoremCategory'),
        ),
        migrations.RunPython(move_data),
        migrations.RemoveField(
            model_name='theorem',
            name='category',
        ),
    ]
