# Generated by Django 2.2.27 on 2022-04-30 11:54

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'properties.json', app_label='ringapp', database='ringapp_data')

class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0056_auto_20220428_0238'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
