# Generated by Django 2.2.28 on 2022-05-01 13:11

from django.db import migrations


database_operations = [
        migrations.AlterModelTable('Suggestion', 'web_suggestion')
    ]

state_operations = [
    migrations.DeleteModel('Suggestion')
]


class Migration(migrations.Migration):
    dependencies = [
        ('ringapp', '0057_auto_20220430_1154'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
