# Generated by Django 2.2.28 on 2022-05-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0058_auto_20220501_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
