# Generated by Django 3.2.14 on 2022-08-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0059_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='logic',
            name='concsnew',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logic',
            name='hypsnew',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
