# Generated by Django 3.2.14 on 2022-08-12 15:27

from django.db import migrations


def convert(propertyside):
    """Change given propertyside into a souffle clause"""
    return f'ring_deduced("has",{propertyside.side},{propertyside.property.id})'


def translate(apps, schema_editor):
    """Translate old lists of propertysides to souffle statements"""
    Logic = apps.get_model('ringapp', 'Logic')
    for logic in Logic.objects.all():
        logic.hypsnew = ' AND '.join([convert(ps) for ps in logic.hyps.all()])
        logic.concsnew = ' AND '.join([convert(ps) for ps in logic.concs.all()])
        logic.save()


def remove_translation(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0060_add_souffle_columns_to_logic'),
    ]

    operations = [
        migrations.RunPython(translate, remove_translation)
    ]
