# Generated by Django 3.2.14 on 2022-08-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0061_migrate_to_souffle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logic',
            name='concs',
        ),
        migrations.RemoveField(
            model_name='logic',
            name='hyps',
        ),
    ]
