# Generated by Django 3.2.14 on 2022-08-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0062_remove_hyps_concs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logic',
            old_name='concsnew',
            new_name='concs',
        ),
        migrations.RenameField(
            model_name='logic',
            old_name='hypsnew',
            new_name='hyps',
        ),
    ]
