# Generated by Django 3.2.14 on 2022-11-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ringapp', '0063_rename_new_hyps_concs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringdimension',
            name='reason_left',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ringdimension',
            name='reason_right',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ringsubset',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
