# Generated by Django 3.2.14 on 2022-09-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleapp', '0001_initial'),
        ('ringapp', '0063_rename_new_hyps_concs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logic',
            name='concsnew',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logic',
            name='hypsnew',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
