# Generated by Django 3.2.14 on 2022-09-22 00:47

from django.db import migrations


def ring_convert(propertyside):
    """Change given propertyside into a souffle clause"""
    return f'ring_deduced("has",{propertyside.side},{propertyside.property.id})'


def module_convert(property):
    return f'module_deduced("has",{property.id})'


def translate(apps, schema_editor):
    """Translate old lists of propertysides to souffle statements"""
    Logic = apps.get_model('moduleapp', 'Logic')
    for logic in Logic.objects.all():
        logic.hypsnew = ' AND '.join([module_convert(prop) for prop in logic.hyps.all()] +
                                     [ring_convert(ps) for ps in logic.ring_hyps.all()])
        logic.concsnew = ' AND '.join([module_convert(prop) for prop in logic.concs.all()])
        logic.save()


def remove_translation(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('moduleapp', '0002_add_souffle_columns_to_logic'),
    ]

    operations = [
        migrations.RunPython(translate, remove_translation)
    ]

