# Generated by Django 3.2.14 on 2022-09-22 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduleapp', '0003_migrate_to_souffle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logic',
            name='concs',
        ),
        migrations.RemoveField(
            model_name='logic',
            name='hyps',
        ),
        migrations.RemoveField(
            model_name='logic',
            name='ring_hyps',
        ),
    ]
