# Generated by Django 3.2.14 on 2022-09-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduleapp', '0004_remove_old_columns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logic',
            old_name='concsnew',
            new_name='concs',
        ),
        migrations.RenameField(
            model_name='logic',
            old_name='hypsnew',
            new_name='hyps',
        ),
    ]
