# Generated by Django 3.2.23 on 2024-02-03 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduleapp', '0005_rename_logic_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('SUBMOD_OF', 'is a submodule of'), ('IMAGE_OF', 'is a homomorphic image of')], max_length=32)),
                ('note', models.TextField(blank=True, max_length=400, null=True)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_module', to='moduleapp.module')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_module', to='moduleapp.module')),
            ],
            options={
                'unique_together': {('first', 'second', 'relation_type')},
            },
        ),
        migrations.AddField(
            model_name='propertymetaproperty',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moduleapp.relation'),
        ),
    ]
